# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.1.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *  # type: ignore
from PySide6.QtGui import *  # type: ignore
from PySide6.QtWidgets import *  # type: ignore


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(872, 664)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 631, 741))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.groupBox = QGroupBox(self.tab)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(0, 370, 261, 231))
        self.label_status_word_dis = QLabel(self.groupBox)
        self.label_status_word_dis.setObjectName(u"label_status_word_dis")
        self.label_status_word_dis.setGeometry(QRect(10, 40, 61, 21))
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 20, 71, 16))
        self.label_oPer_mode = QLabel(self.groupBox)
        self.label_oPer_mode.setObjectName(u"label_oPer_mode")
        self.label_oPer_mode.setGeometry(QRect(160, 20, 71, 16))
        self.label_oPer_mode.setFocusPolicy(Qt.TabFocus)
        self.label_oPer_mode_dis = QLabel(self.groupBox)
        self.label_oPer_mode_dis.setObjectName(u"label_oPer_mode_dis")
        self.label_oPer_mode_dis.setGeometry(QRect(160, 40, 49, 16))
        self.label_oPer_mode_dis.setFrameShadow(QFrame.Sunken)
        self.label_oPer_mode_dis.setTextFormat(Qt.PlainText)
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(0, 170, 121, 20))
        self.label_actual_position = QLabel(self.groupBox)
        self.label_actual_position.setObjectName(u"label_actual_position")
        self.label_actual_position.setGeometry(QRect(130, 170, 49, 16))
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(0, 150, 111, 20))
        self.label_actual_velocity = QLabel(self.groupBox)
        self.label_actual_velocity.setObjectName(u"label_actual_velocity")
        self.label_actual_velocity.setGeometry(QRect(130, 150, 49, 16))
        self.label_9 = QLabel(self.groupBox)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(0, 190, 131, 20))
        self.label_actual_position_degree = QLabel(self.groupBox)
        self.label_actual_position_degree.setObjectName(u"label_actual_position_degree")
        self.label_actual_position_degree.setGeometry(QRect(130, 190, 49, 16))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 80, 111, 16))
        self.label_bit_0_copy = QLabel(self.groupBox)
        self.label_bit_0_copy.setObjectName(u"label_bit_0_copy")
        self.label_bit_0_copy.setGeometry(QRect(10, 100, 49, 20))
        self.groupBox_2 = QGroupBox(self.tab)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(0, 280, 301, 81))
        self.turn_on_Button = QPushButton(self.groupBox_2)
        self.turn_on_Button.setObjectName(u"turn_on_Button")
        self.turn_on_Button.setGeometry(QRect(10, 20, 75, 24))
        self.turn_off_Button = QPushButton(self.groupBox_2)
        self.turn_off_Button.setObjectName(u"turn_off_Button")
        self.turn_off_Button.setGeometry(QRect(10, 50, 75, 24))
        self.Motor_status = QLabel(self.groupBox_2)
        self.Motor_status.setObjectName(u"Motor_status")
        self.Motor_status.setGeometry(QRect(230, 10, 71, 20))
        self.groupBox_3 = QGroupBox(self.tab)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(0, 0, 321, 271))
        self.lineEdit = QLineEdit(self.groupBox_3)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(0, 40, 111, 22))
        self.lineEdit_2 = QLineEdit(self.groupBox_3)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(0, 90, 113, 22))
        self.label_2 = QLabel(self.groupBox_3)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 70, 101, 16))
        self.comboBox = QComboBox(self.groupBox_3)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(0, 20, 141, 22))
        self.start_motor = QPushButton(self.groupBox_3)
        self.start_motor.setObjectName(u"start_motor")
        self.start_motor.setGeometry(QRect(0, 120, 75, 24))
        self.Homingbutton = QPushButton(self.groupBox_3)
        self.Homingbutton.setObjectName(u"Homingbutton")
        self.Homingbutton.setGeometry(QRect(0, 200, 75, 24))
        self.rel_radio_button = QRadioButton(self.groupBox_3)
        self.rel_radio_button.setObjectName(u"rel_radio_button")
        self.rel_radio_button.setGeometry(QRect(170, 40, 131, 20))
        self.abs_radio_button = QRadioButton(self.groupBox_3)
        self.abs_radio_button.setObjectName(u"abs_radio_button")
        self.abs_radio_button.setGeometry(QRect(170, 70, 131, 20))
        self.vel_radio_button = QRadioButton(self.groupBox_3)
        self.vel_radio_button.setObjectName(u"vel_radio_button")
        self.vel_radio_button.setGeometry(QRect(170, 100, 121, 20))
        self.stop_motor = QPushButton(self.groupBox_3)
        self.stop_motor.setObjectName(u"stop_motor")
        self.stop_motor.setGeometry(QRect(0, 160, 75, 23))
        self.reference_button = QPushButton(self.groupBox_3)
        self.reference_button.setObjectName(u"reference_button")
        self.reference_button.setGeometry(QRect(0, 250, 75, 24))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.label_status_0 = QLabel(self.tab_2)
        self.label_status_0.setObjectName(u"label_status_0")
        self.label_status_0.setGeometry(QRect(10, 60, 111, 20))
        self.label_status_8 = QLabel(self.tab_2)
        self.label_status_8.setObjectName(u"label_status_8")
        self.label_status_8.setGeometry(QRect(0, 310, 121, 20))
        self.label_status_3 = QLabel(self.tab_2)
        self.label_status_3.setObjectName(u"label_status_3")
        self.label_status_3.setGeometry(QRect(0, 160, 131, 20))
        self.label_status_7 = QLabel(self.tab_2)
        self.label_status_7.setObjectName(u"label_status_7")
        self.label_status_7.setGeometry(QRect(0, 280, 121, 20))
        self.label_bit_12 = QLabel(self.tab_2)
        self.label_bit_12.setObjectName(u"label_bit_12")
        self.label_bit_12.setGeometry(QRect(140, 430, 49, 16))
        self.label_bit_11 = QLabel(self.tab_2)
        self.label_bit_11.setObjectName(u"label_bit_11")
        self.label_bit_11.setGeometry(QRect(140, 400, 49, 16))
        self.label_status_10 = QLabel(self.tab_2)
        self.label_status_10.setObjectName(u"label_status_10")
        self.label_status_10.setGeometry(QRect(0, 370, 101, 20))
        self.label_bit_15 = QLabel(self.tab_2)
        self.label_bit_15.setObjectName(u"label_bit_15")
        self.label_bit_15.setGeometry(QRect(140, 540, 49, 16))
        self.label_bit_6 = QLabel(self.tab_2)
        self.label_bit_6.setObjectName(u"label_bit_6")
        self.label_bit_6.setGeometry(QRect(140, 250, 49, 16))
        self.label_bit_8 = QLabel(self.tab_2)
        self.label_bit_8.setObjectName(u"label_bit_8")
        self.label_bit_8.setGeometry(QRect(140, 310, 49, 16))
        self.label_status_9 = QLabel(self.tab_2)
        self.label_status_9.setObjectName(u"label_status_9")
        self.label_status_9.setGeometry(QRect(0, 340, 91, 20))
        self.label_status_13 = QLabel(self.tab_2)
        self.label_status_13.setObjectName(u"label_status_13")
        self.label_status_13.setGeometry(QRect(0, 470, 91, 20))
        self.label_status_6 = QLabel(self.tab_2)
        self.label_status_6.setObjectName(u"label_status_6")
        self.label_status_6.setGeometry(QRect(10, 250, 91, 20))
        self.label_bit_1 = QLabel(self.tab_2)
        self.label_bit_1.setObjectName(u"label_bit_1")
        self.label_bit_1.setGeometry(QRect(140, 90, 49, 16))
        self.label_bit_2 = QLabel(self.tab_2)
        self.label_bit_2.setObjectName(u"label_bit_2")
        self.label_bit_2.setGeometry(QRect(140, 120, 49, 16))
        self.label_status_2 = QLabel(self.tab_2)
        self.label_status_2.setObjectName(u"label_status_2")
        self.label_status_2.setGeometry(QRect(10, 120, 111, 20))
        self.label_status_5 = QLabel(self.tab_2)
        self.label_status_5.setObjectName(u"label_status_5")
        self.label_status_5.setGeometry(QRect(0, 220, 111, 20))
        self.label_status_11 = QLabel(self.tab_2)
        self.label_status_11.setObjectName(u"label_status_11")
        self.label_status_11.setGeometry(QRect(0, 400, 101, 20))
        self.label_status_15 = QLabel(self.tab_2)
        self.label_status_15.setObjectName(u"label_status_15")
        self.label_status_15.setGeometry(QRect(0, 510, 91, 20))
        self.label_status_12 = QLabel(self.tab_2)
        self.label_status_12.setObjectName(u"label_status_12")
        self.label_status_12.setGeometry(QRect(10, 430, 101, 20))
        self.label_bit_9 = QLabel(self.tab_2)
        self.label_bit_9.setObjectName(u"label_bit_9")
        self.label_bit_9.setGeometry(QRect(140, 340, 49, 16))
        self.label_bit_4 = QLabel(self.tab_2)
        self.label_bit_4.setObjectName(u"label_bit_4")
        self.label_bit_4.setGeometry(QRect(140, 190, 49, 20))
        self.label_status_1 = QLabel(self.tab_2)
        self.label_status_1.setObjectName(u"label_status_1")
        self.label_status_1.setGeometry(QRect(0, 90, 111, 20))
        self.label_bit_0 = QLabel(self.tab_2)
        self.label_bit_0.setObjectName(u"label_bit_0")
        self.label_bit_0.setGeometry(QRect(140, 60, 49, 16))
        self.label_bit_14 = QLabel(self.tab_2)
        self.label_bit_14.setObjectName(u"label_bit_14")
        self.label_bit_14.setGeometry(QRect(140, 510, 49, 16))
        self.label_bit_3 = QLabel(self.tab_2)
        self.label_bit_3.setObjectName(u"label_bit_3")
        self.label_bit_3.setGeometry(QRect(140, 160, 49, 16))
        self.label_bit_5 = QLabel(self.tab_2)
        self.label_bit_5.setObjectName(u"label_bit_5")
        self.label_bit_5.setGeometry(QRect(140, 220, 49, 16))
        self.label_status_4 = QLabel(self.tab_2)
        self.label_status_4.setObjectName(u"label_status_4")
        self.label_status_4.setGeometry(QRect(0, 190, 111, 20))
        self.label_bit_7 = QLabel(self.tab_2)
        self.label_bit_7.setObjectName(u"label_bit_7")
        self.label_bit_7.setGeometry(QRect(140, 280, 49, 16))
        self.label_bit_10 = QLabel(self.tab_2)
        self.label_bit_10.setObjectName(u"label_bit_10")
        self.label_bit_10.setGeometry(QRect(140, 370, 49, 16))
        self.label_status_14 = QLabel(self.tab_2)
        self.label_status_14.setObjectName(u"label_status_14")
        self.label_status_14.setGeometry(QRect(0, 540, 111, 20))
        self.label_bit_13 = QLabel(self.tab_2)
        self.label_bit_13.setObjectName(u"label_bit_13")
        self.label_bit_13.setGeometry(QRect(140, 470, 49, 16))
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 872, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Device  Status", None))
        self.label_status_word_dis.setText(QCoreApplication.translate("MainWindow", u"Status word ", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Status_word", None))
        self.label_oPer_mode.setText(QCoreApplication.translate("MainWindow", u"Oper.Mode", None))
        self.label_oPer_mode_dis.setText(QCoreApplication.translate("MainWindow", u"oper.Mode", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Actual position(Turns)", None))
        self.label_actual_position.setText(QCoreApplication.translate("MainWindow", u"actual_positon", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Actual velocity(U/s)", None))
        self.label_actual_velocity.setText(QCoreApplication.translate("MainWindow", u"acl_velocity", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Actual position(Degree)", None))
        self.label_actual_position_degree.setText(QCoreApplication.translate("MainWindow", u"actual_positon", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Reference found", None))
        self.label_bit_0_copy.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Power-on/off", None))
        self.turn_on_Button.setText(QCoreApplication.translate("MainWindow", u"Turn_on", None))
        self.turn_off_Button.setText(QCoreApplication.translate("MainWindow", u"Turn_off", None))
        self.Motor_status.setText("")
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Operation modes", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Velocity  U/s", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Turns", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"Degree", None))

        self.start_motor.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.Homingbutton.setText(QCoreApplication.translate("MainWindow", u"Homing", None))
        self.rel_radio_button.setText(QCoreApplication.translate("MainWindow", u"Relative positioning", None))
        self.abs_radio_button.setText(QCoreApplication.translate("MainWindow", u"Absolute positioning", None))
        self.vel_radio_button.setText(QCoreApplication.translate("MainWindow", u"Velocity mode", None))
        self.stop_motor.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.reference_button.setText(QCoreApplication.translate("MainWindow", u"Set reference", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Motion", None))
        self.label_status_0.setText(QCoreApplication.translate("MainWindow", u"Reference found", None))
        self.label_status_8.setText(QCoreApplication.translate("MainWindow", u"Warning  ", None))
        self.label_status_3.setText(QCoreApplication.translate("MainWindow", u"Setpoint Acknowledge", None))
        self.label_status_7.setText(QCoreApplication.translate("MainWindow", u"Manufacturer specific", None))
        self.label_bit_12.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_bit_11.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_status_10.setText(QCoreApplication.translate("MainWindow", u"Quick Stop", None))
        self.label_bit_15.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_bit_6.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_bit_8.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_status_9.setText(QCoreApplication.translate("MainWindow", u"Switch on Disable", None))
        self.label_status_13.setText(QCoreApplication.translate("MainWindow", u"Operation Enable", None))
        self.label_status_6.setText(QCoreApplication.translate("MainWindow", u"Reserved", None))
        self.label_bit_1.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_bit_2.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_status_2.setText(QCoreApplication.translate("MainWindow", u"Reference error", None))
        self.label_status_5.setText(QCoreApplication.translate("MainWindow", u"Target reached", None))
        self.label_status_11.setText(QCoreApplication.translate("MainWindow", u"Voltage Enabled", None))
        self.label_status_15.setText(QCoreApplication.translate("MainWindow", u"Switched on", None))
        self.label_status_12.setText(QCoreApplication.translate("MainWindow", u"Fault", None))
        self.label_bit_9.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_bit_4.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_status_1.setText(QCoreApplication.translate("MainWindow", u"Commutation found", None))
        self.label_bit_0.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_bit_14.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_bit_3.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_bit_5.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_status_4.setText(QCoreApplication.translate("MainWindow", u"Internal limit active", None))
        self.label_bit_7.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_bit_10.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_status_14.setText(QCoreApplication.translate("MainWindow", u"Ready to switch on", None))
        self.label_bit_13.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Status word", None))
    # retranslateUi

